### ISSUE TITLE
Toggle switches / settings bleed between maps

### ISSUE THREAD

**Issue by cstephen** [ua-snap/mapvue#11]
Load any one of the maps. Then:

1. Click "Split / single map" to enable split maps.
2. Click the "About this site & other maps" link in the footer.
3. Go to a different map, which will load with split maps already enabled.

The same thing applies to the "Graph large fire seasons" button. Once we finish our refactor job this button will only appear on the Fire map. But for now:

1. Go to the RCP or IAM map, click the "Graph large fire seasons" button. It won't do anything (that's expected).
2. Click the "About this site & other maps" link in the footer.
3. Go to the Fire map, which will load with the large fire seasons graph already opened.

It appears that all map state settings carry over from one map to another as long as you navigate to the new map using the footer link instead of changing the URL in the address bar. I think the solution here is just to reset all these states back to their defaults when loading a map.

**Comment by brucecrevensten** [comment]
Fixed in eb7909ecb8f33f8fb28b5d5fac79d7a8c4d3385d
