### ISSUE TITLE
Fire graph loads too small on maximized browser window

### ISSUE THREAD

**Issue by cstephen** [ua-snap/mapvue#14]
I thought this was working properly before, but if I maximize my browser window (before loading the Fire map page) then click the "Graph large fire seasons..." button, it loads like this:

![image](https://user-images.githubusercontent.com/2566292/32248204-b8ec87b0-be39-11e7-8e45-05a8256eaf75.png)

**Comment by brucecrevensten** [comment]
I think we can also safely say that the opposite is true; on a really narrow screen, the graph is too big! (Artificially induced example below):

<img width="809" alt="screen shot 2017-11-28 at 2 04 02 pm" src="https://user-images.githubusercontent.com/525049/33346563-0738e802-d445-11e7-82f9-c72393d1538b.png">
