### ISSUE TITLE
Jumping to the fire graph from main menu results in a reduced size div for graph

### ISSUE THREAD

**Issue by BobTorgerson** [ua-snap/mapvue#176]
STR this issue:

1. Go to http://localhost:8080
2. Change the URL to http://localhost:8080/#/map/fires/graph

Note the close button is outside the div. This does not happen if you go to the fire graph and then change the URL to the fire graph.

<img width="1439" alt="graph_from_main_menu" src="https://user-images.githubusercontent.com/563260/61083863-3988ad00-a3d9-11e9-8496-8d47e062d837.png">

**Comment by brucecrevensten** [comment]
Hmm, I can't quite get this to happen again -- also I notice that there are _two_ legends in the chart that loaded for you, which is why the layout is goofed.  How on earth did that happen?  Will keep trying to see if it happens again!

**Comment by brucecrevensten** [comment]
Closed because this is now moved to a new tool.
