### ISSUE TITLE
Month and Date Selector Issue

### ISSUE THREAD

**Issue by BobTorgerson** [ua-snap/mapvue#203]
When the month for Historical Lightning Strikes in AK Fires map or the date for the SNAP Climate map is changed, when you close the layer, it will keep the month or date in the title, but when it re-opens it will have the default month or date listed in the drop down menu without changing the title. 

STR:

1. Go into AK Fires Map
2. Open Historical Lightning Strikes and change to June
3. Close the Historical Lightning Strikes layer
Note the month on the layer
4. Open the Historical Lightning Strikes layer again
Note the month in the drop down menu in comparison to the title.

Expected: The month should either change in the title to the default or the dropdown should be set to what the title states.

**Comment by brucecrevensten** [comment]
Good find, and x-ref #189, there's clearly something fishy here with persisting state.
