### ISSUE TITLE
All fire and lightning icons do not adjust their Z-level with movement in map layer list

### ISSUE THREAD

**Issue by BobTorgerson** [ua-snap/mapvue#97]
Both the All fires, 2018 and last two days lightning icons are not respecting Z-level ordering on the map layer list like all of the other raster layers do in the map.

**Comment by brucecrevensten** [comment]
Generally, this could only probably be solved if we created a custom range of Leaflet pane objects and managed those manually.  By default, all the tile layers go into the `tilePane` pane, while markers and polygons go into `markerPane` and `overlayPane`, respectively; these have a higher z-index than `tilePane`.

Not sure if the effort required is worthwhile.  If any map demonstrates a need for this, it'd be the Fire map, but I'm not sure if it's strictly necessary even there.

Closing, but feel free to reopen!
